export enum ERROR_TYPES {
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_UPDATES = 'INVALID_UPDATES',
  INVALID_TRANSACTION = 'INVALID_TRANSACTION',
  INVALID_INVITE = 'INVALID_INVITE',
  CANNOT_JOIN_GROUP = 'CANNOT_JOIN_GROUP',
}

export const ERROR_CODES_MAP: Record<ERROR_TYPES, number> = {
  [ERROR_TYPES.UNAUTHORIZED]: 401,
  [ERROR_TYPES.INVALID_UPDATES]: 400,
  [ERROR_TYPES.INVALID_TRANSACTION]: 400,
  [ERROR_TYPES.INVALID_INVITE]: 400,
  [ERROR_TYPES.CANNOT_JOIN_GROUP]: 400,
}
