# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/react'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/react-dom'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'default-import'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'eslint'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'eslint-config-next'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'next'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'react'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'react-dom'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'tailwindcss'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'tailwind-merge'
        update-types:
          - 'version-update:semver-major'
