networks:
  vlad-iakovlev-dev:
    name: vlad-iakovlev-dev

services:
  expense:
    image: ghcr.io/vlad-iakovlev/expense:latest
    pull_policy: always
    build: .
    networks:
      - vlad-iakovlev-dev
    env_file: .env
    environment:
      VIRTUAL_HOST: expense.vlad-iakovlev.dev
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: expense.vlad-iakovlev.dev
    restart: always
