FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/client ./packages/client
COPY packages/schemas ./packages/schemas
COPY tsconfig.json ./

RUN npm ci
RUN npm run build:client

FROM nginx:1.28-alpine AS runner

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/packages/client/dist /usr/share/nginx/html

EXPOSE 80
