networks:
  expense:
    name: expense

services:
  app:
    build: .
    depends_on:
      - mongo
    networks:
      - expense
    environment:
      MONGO_URL: mongodb://mongo:27017/main
    restart: always

  mongo:
    image: mongo:5.0
    networks:
      - expense
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - $PWD/db:/data/db
    healthcheck:
      test: |
        test $$(mongo --quiet --eval "rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo' }] }).ok || rs.status().ok") -eq 1
      interval: 10s
      start_period: 30s
    command: '--bind_ip_all --replSet rs0'
    restart: always
