services:
  expense-server:
    image: ghcr.io/vlad-iakovlev/expense-server:latest
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file: .env
    restart: unless-stopped

  expense-client:
    image: ghcr.io/vlad-iakovlev/expense-client:latest
    pull_policy: always
    depends_on:
      - expense-server
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: unless-stopped
