networks:
  vlad-yakovlev-dev:
    name: vlad-yakovlev-dev

services:
  expense:
    build: .
    networks:
      - vlad-yakovlev-dev
    environment:
      MONGO_URL: mongodb://mongo:27017/expense
    restart: always
