networks:
  vlad-yakovlev-dev:
    name: vlad-yakovlev-dev

services:
  expense:
    image: ghcr.io/vlad-iakovlev/expense:latest
    pull_policy: always
    build: .
    networks:
      - vlad-yakovlev-dev
    env_file: .env
    environment:
      VIRTUAL_HOST: expense.vlad-yakovlev.dev
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: expense.vlad-yakovlev.dev
    restart: always
