name: Update Currency Rates

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-currency-rates:
    if: startsWith(github.repository, 'vlad-iakovlev/')
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron/update-currency-rates endpoint
        uses: tyrrrz/action-http-request@master
        with:
          url: https://expense.vlad-yakovlev.dev/api/cron/update-currency-rates
          method: POST
          headers: |
            Authorization: Bearer ${{ secrets.CRON_SECRET }}
