name: Update Rates

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-rates:
    if: github.repository == 'vlad-yakovlev/expense' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Call update-rates script in Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd Projects/expense
            docker compose exec expense npm run update-rates
