name: Update Currency Rates

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-currency-names:
    if: startsWith(github.repository, 'vlad-yakovlev/')
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron/update-currency-rates endpoint
        run: |
          curl --request POST \
          --url 'https://expense.vlad-yakovlev.dev/api/cron/update-currency-rates' \
          --header 'Authorization: Bearer ${{secrets.CRON_SECRET}}'
