name: Update Currency Names

on:
  workflow_dispatch:

jobs:
  update-currency-names:
    if: github.repository == 'vlad-yakovlev/expense'
    runs-on: ubuntu-latest
    steps:
      - name: Call update-currency-names script in Digital Ocean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd Projects/expense
            docker compose exec expense npm run update-currency-names
