name: Update Currency Names

on:
  workflow_dispatch:

jobs:
  update-currency-names:
    if: startsWith(github.repository, 'vlad-yakovlev/')
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron/update-currency-names endpoint
        uses: tyrrrz/action-http-request@master
        with:
          url: https://expense.vlad-yakovlev.dev/api/cron/update-currency-names
          method: POST
          headers: |
            Authorization: Bearer ${{ secrets.CRON_SECRET }}
